name: buildbook
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - pandas=1.0.5
  - jupyterlab
  - matplotlib
  - pip=20
  - pip:
    - jupyter-book
    - ghp-import
    - plotly==4.1.1
