# Book settings
title: UK COVID-19 Stuff
author: Alex Coleman
email: alexjcoleman@gmail.com
copyright: "2020"

# execute settings
execute:
  execute_notebooks: auto

# HTML-specific settings
html:
  favicon                   : ""  # A path to a favicon image
  navbar_number_sections    : False  # Add a number to each section in your left navbar
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  baseurl                   : "https://sparrow0hawk.github.io/covid_stuff/"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  navbar_footer_text        :
    <div>
    This book is powered by <a href="https://jupyterbook.org">Jupyter Book</a>
    </div>'  # Will be displayed underneath the left navbar.


# Launch button settings
launch_buttons:
  notebook_interface        : "classic"  # The interface interactive links will activate ["classic", "jupyterlab"]
colab_url                   : "https://colab.research.google.com"

repository:
  url                       : https://github.com/sparrow0hawk/covid_stuff  # The URL to your book's repository
  path_to_book              : "book/"  # A path to your book's folder, relative to the repository root.
  branch                    : master  # Which branch of the repository should be used when creating links

